# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  oh-my-pi-darwin-arm64 = {
    pname = "oh-my-pi-darwin-arm64";
    version = "v17.2.12";
    src = fetchurl {
      url = "https://github.com/can1357/oh-my-pi/releases/download/v17.2.12/omp-darwin-arm64";
      sha256 = "sha256-q0/yTIujrm/Z1LVJaclPRAjMMWZ19VNHKa5QLYyX33Q=";
    };
  };
  oh-my-pi-darwin-x64 = {
    pname = "oh-my-pi-darwin-x64";
    version = "v17.2.12";
    src = fetchurl {
      url = "https://github.com/can1357/oh-my-pi/releases/download/v17.2.12/omp-darwin-x64";
      sha256 = "sha256-7eUWJYc7t+WSAHEevkS3dZGaGLRv6SeZWkH5MVqclqo=";
    };
  };
  oh-my-pi-linux-arm64 = {
    pname = "oh-my-pi-linux-arm64";
    version = "v17.2.12";
    src = fetchurl {
      url = "https://github.com/can1357/oh-my-pi/releases/download/v17.2.12/omp-linux-arm64";
      sha256 = "sha256-8Xbt+BdNslKr4apuhN8oThuDuN1+80rH+veISl4XKkw=";
    };
  };
  oh-my-pi-linux-x64 = {
    pname = "oh-my-pi-linux-x64";
    version = "v17.2.12";
    src = fetchurl {
      url = "https://github.com/can1357/oh-my-pi/releases/download/v17.2.12/omp-linux-x64";
      sha256 = "sha256-bHUzG/CdWp6UM71ZKz7pk9dRoV1bdFDBozTMBoSZbzA=";
    };
  };
}
