[nordic-wallpaper]
src.git = "https://github.com/linuxdotexe/nordic-wallpapers"
fetch.github = "linuxdotexe/nordic-wallpapers"

[pop-wallpaper]
src.github = "George-Miao/wallpaper"
fetch.github = "George-Miao/wallpaper"

[vscode-linux-x64-stable]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=stable&os=linux-x64'"""
fetch.tarball = "$ver"

[vscode-linux-x64-insider]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=insider&os=linux-x64'"""
fetch.tarball = "$ver"

[vscode-linux-arm64-stable]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=stable&os=linux-arm64'"""
fetch.tarball = "$ver"

[vscode-linux-arm64-insider]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=insider&os=linux-arm64'"""
fetch.tarball = "$ver"

[vscode-darwin-stable]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=stable&os=darwin-universal'"""
fetch.tarball = "$ver"

[vscode-darwin-insider]
src.cmd = """curl -Ls -o /dev/null -w %{url_effective} 'https://code.visualstudio.com/sha/download?build=insider&os=darwin-universal'"""
fetch.tarball = "$ver"

[verus-linux-x64]
src.cmd = """curl -s https://api.github.com/repos/verus-lang/verus/releases/latest | jq -r '.tag_name | split("/") | last'"""
fetch.tarball = "https://github.com/verus-lang/verus/releases/download/release%2F$ver/verus-$ver-x86-linux.zip"

[verus-darwin-x64]
src.cmd = """curl -s https://api.github.com/repos/verus-lang/verus/releases/latest | jq -r '.tag_name | split("/") | last'"""
fetch.tarball = "https://github.com/verus-lang/verus/releases/download/release%2F$ver/verus-$ver-x86-macos.zip"

[verus-darwin-arm64]
src.cmd = """curl -s https://api.github.com/repos/verus-lang/verus/releases/latest | jq -r '.tag_name | split("/") | last'"""
fetch.tarball = "https://github.com/verus-lang/verus/releases/download/release%2F$ver/verus-$ver-arm64-macos.zip"
