# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nordic-wallpaper = {
    pname = "nordic-wallpaper";
    version = "7a8e3bcabafbefd1c5b19229841b9bf377a4b765";
    src = fetchFromGitHub {
      owner = "linuxdotexe";
      repo = "nordic-wallpapers";
      rev = "7a8e3bcabafbefd1c5b19229841b9bf377a4b765";
      fetchSubmodules = false;
      sha256 = "sha256-clRGfUqKD4/v5bNj/lI5pKDdf6qraZXJBWZtBLLqF50=";
    };
    date = "2025-12-31";
  };
  pop-wallpaper = {
    pname = "pop-wallpaper";
    version = "f79c2e";
    src = fetchFromGitHub {
      owner = "George-Miao";
      repo = "wallpaper";
      rev = "f79c2e";
      fetchSubmodules = false;
      sha256 = "sha256-3VYnGGE/N8GWGWTCHYFQxMva1Ye8NIaByfzBCCyPUPU=";
    };
  };
  vscode-linux-arm64-insider = {
    pname = "vscode-linux-arm64-insider";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/c308cc9f87e1427a73c5e32c81a1cfe9b1b203d1/code-insider-arm64-1770398942.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/c308cc9f87e1427a73c5e32c81a1cfe9b1b203d1/code-insider-arm64-1770398942.tar.gz";
      sha256 = "sha256-6N8r4W+zl1qWPbqnfniV19zXqkmowbSqKor1DYMg9iA=";
    };
  };
  vscode-linux-arm64-stable = {
    pname = "vscode-linux-arm64-stable";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/bdd88df003631aaa0bcbe057cb0a940b80a476fa/code-stable-arm64-1770171785.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/bdd88df003631aaa0bcbe057cb0a940b80a476fa/code-stable-arm64-1770171785.tar.gz";
      sha256 = "sha256-089Q8+p/dlbMSnE6xfqlScEj99BjAhyd57kJJ+fnmtU=";
    };
  };
  vscode-linux-x64-insider = {
    pname = "vscode-linux-x64-insider";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/c308cc9f87e1427a73c5e32c81a1cfe9b1b203d1/code-insider-x64-1770398978.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/c308cc9f87e1427a73c5e32c81a1cfe9b1b203d1/code-insider-x64-1770398978.tar.gz";
      sha256 = "sha256-p18I4eq5UEM2TFi+6d+d530im+3Z2ZBXYYVidBXss88=";
    };
  };
  vscode-linux-x64-stable = {
    pname = "vscode-linux-x64-stable";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/bdd88df003631aaa0bcbe057cb0a940b80a476fa/code-stable-x64-1770171784.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/bdd88df003631aaa0bcbe057cb0a940b80a476fa/code-stable-x64-1770171784.tar.gz";
      sha256 = "sha256-lBvdi9XhqCaMUNcwoR1uw/+Q+cPWLhWkxPJaRkg6MFk=";
    };
  };
}
