# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nordic-wallpaper = {
    pname = "nordic-wallpaper";
    version = "7a8e3bcabafbefd1c5b19229841b9bf377a4b765";
    src = fetchFromGitHub {
      owner = "linuxdotexe";
      repo = "nordic-wallpapers";
      rev = "7a8e3bcabafbefd1c5b19229841b9bf377a4b765";
      fetchSubmodules = false;
      sha256 = "sha256-clRGfUqKD4/v5bNj/lI5pKDdf6qraZXJBWZtBLLqF50=";
    };
    date = "2025-12-31";
  };
  pop-wallpaper = {
    pname = "pop-wallpaper";
    version = "f79c2e";
    src = fetchFromGitHub {
      owner = "George-Miao";
      repo = "wallpaper";
      rev = "f79c2e";
      fetchSubmodules = false;
      sha256 = "sha256-3VYnGGE/N8GWGWTCHYFQxMva1Ye8NIaByfzBCCyPUPU=";
    };
  };
  verus-darwin-arm64 = {
    pname = "verus-darwin-arm64";
    version = "0.2026.05.03.8b81855";
    src = fetchTarball {
      url = "https://github.com/verus-lang/verus/releases/download/release%2F0.2026.05.03.8b81855/verus-0.2026.05.03.8b81855-arm64-macos.zip";
      sha256 = "sha256-k2pV668GvGlVzS0v9QHzyUjIX8OpqMGLcltrCetkSJI=";
    };
  };
  verus-darwin-x64 = {
    pname = "verus-darwin-x64";
    version = "0.2026.05.03.8b81855";
    src = fetchTarball {
      url = "https://github.com/verus-lang/verus/releases/download/release%2F0.2026.05.03.8b81855/verus-0.2026.05.03.8b81855-x86-macos.zip";
      sha256 = "sha256-/fF9G7/1I/t7LrmoI+JMexDPxNkJkxanGLhSxa1Jk10=";
    };
  };
  verus-linux-x64 = {
    pname = "verus-linux-x64";
    version = "0.2026.05.03.8b81855";
    src = fetchTarball {
      url = "https://github.com/verus-lang/verus/releases/download/release%2F0.2026.05.03.8b81855/verus-0.2026.05.03.8b81855-x86-linux.zip";
      sha256 = "sha256-cU4p7Jy+C0/T/xhi1vxMoUhpp93dVWl6pwlVRNjg3VU=";
    };
  };
  verusfmt = {
    pname = "verusfmt";
    version = "v0.7.0";
    src = fetchFromGitHub {
      owner = "verus-lang";
      repo = "verusfmt";
      rev = "v0.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-H9vD67Jrxrt515Wjd696Aoqc1n5LuxCaSxIXX9dNEZw=";
    };
  };
  vscode-darwin-insider = {
    pname = "vscode-darwin-insider";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/89bab60dbb6cdd0d1394f011e110457d885b9fa3/VSCode-darwin.zip";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/89bab60dbb6cdd0d1394f011e110457d885b9fa3/VSCode-darwin.zip";
      sha256 = "sha256-MV8CvLALPztRyki95JxZivWXsYHjxli1ETO+/Slbz4c=";
    };
  };
  vscode-darwin-stable = {
    pname = "vscode-darwin-stable";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/8b640eef5a6c6089c029249d48efa5c99adf7d51/VSCode-darwin.zip";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/8b640eef5a6c6089c029249d48efa5c99adf7d51/VSCode-darwin.zip";
      sha256 = "sha256-gDJ4AjD1HzFmALtTzmTFIcNzK3JEt9DLlqD7fBj0Ja0=";
    };
  };
  vscode-linux-arm64-insider = {
    pname = "vscode-linux-arm64-insider";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/89bab60dbb6cdd0d1394f011e110457d885b9fa3/code-insider-arm64-1778217400.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/89bab60dbb6cdd0d1394f011e110457d885b9fa3/code-insider-arm64-1778217400.tar.gz";
      sha256 = "sha256-iJeIyWcDuZ4bMsUXT4HPX+MQ48mIQfXzTCqD8kfkCX4=";
    };
  };
  vscode-linux-arm64-stable = {
    pname = "vscode-linux-arm64-stable";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/8b640eef5a6c6089c029249d48efa5c99adf7d51/code-stable-arm64-1778006632.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/8b640eef5a6c6089c029249d48efa5c99adf7d51/code-stable-arm64-1778006632.tar.gz";
      sha256 = "sha256-B6Dsgy3D8VtdaYbEzGCWbz7DklMCOypJbxtBFh3oBQo=";
    };
  };
  vscode-linux-x64-insider = {
    pname = "vscode-linux-x64-insider";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/89bab60dbb6cdd0d1394f011e110457d885b9fa3/code-insider-x64-1778217399.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/89bab60dbb6cdd0d1394f011e110457d885b9fa3/code-insider-x64-1778217399.tar.gz";
      sha256 = "sha256-1UQLsoh3rWvS1FjRqlRvgWOZz6j3/nRkx/exu8CUXxw=";
    };
  };
  vscode-linux-x64-stable = {
    pname = "vscode-linux-x64-stable";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/8b640eef5a6c6089c029249d48efa5c99adf7d51/code-stable-x64-1778006615.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/8b640eef5a6c6089c029249d48efa5c99adf7d51/code-stable-x64-1778006615.tar.gz";
      sha256 = "sha256-Gfm8z484KiVrU1THJKxvZ5RKbwJlyZ+v91QQifY5dn8=";
    };
  };
}
