# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nordic-wallpaper = {
    pname = "nordic-wallpaper";
    version = "7a8e3bcabafbefd1c5b19229841b9bf377a4b765";
    src = fetchFromGitHub {
      owner = "linuxdotexe";
      repo = "nordic-wallpapers";
      rev = "7a8e3bcabafbefd1c5b19229841b9bf377a4b765";
      fetchSubmodules = false;
      sha256 = "sha256-clRGfUqKD4/v5bNj/lI5pKDdf6qraZXJBWZtBLLqF50=";
    };
    date = "2025-12-31";
  };
  pop-wallpaper = {
    pname = "pop-wallpaper";
    version = "f79c2e";
    src = fetchFromGitHub {
      owner = "George-Miao";
      repo = "wallpaper";
      rev = "f79c2e";
      fetchSubmodules = false;
      sha256 = "sha256-3VYnGGE/N8GWGWTCHYFQxMva1Ye8NIaByfzBCCyPUPU=";
    };
  };
  verus-darwin-arm64 = {
    pname = "verus-darwin-arm64";
    version = "0.2026.06.20.911e4e7";
    src = fetchTarball {
      url = "https://github.com/verus-lang/verus/releases/download/release%2F0.2026.06.20.911e4e7/verus-0.2026.06.20.911e4e7-arm64-macos.zip";
      sha256 = "sha256-AvOma6LQZr+/U/fuu3rpP+7rwN0l35pBJidSdowlvSc=";
    };
  };
  verus-darwin-x64 = {
    pname = "verus-darwin-x64";
    version = "0.2026.06.20.911e4e7";
    src = fetchTarball {
      url = "https://github.com/verus-lang/verus/releases/download/release%2F0.2026.06.20.911e4e7/verus-0.2026.06.20.911e4e7-x86-macos.zip";
      sha256 = "sha256-VfD08fSxM7XbJqv9pWP110pmdXgWJYvcn2hUo01glDc=";
    };
  };
  verus-linux-x64 = {
    pname = "verus-linux-x64";
    version = "0.2026.06.20.911e4e7";
    src = fetchTarball {
      url = "https://github.com/verus-lang/verus/releases/download/release%2F0.2026.06.20.911e4e7/verus-0.2026.06.20.911e4e7-x86-linux.zip";
      sha256 = "sha256-FnA3KCyQaxNR+iQUhZPIJbPeDDrD/c7iZY6SAdLWpBg=";
    };
  };
  verusfmt = {
    pname = "verusfmt";
    version = "v0.7.2";
    src = fetchFromGitHub {
      owner = "verus-lang";
      repo = "verusfmt";
      rev = "v0.7.2";
      fetchSubmodules = false;
      sha256 = "sha256-TE1Qyk5y8G/Kid6/BmUIMZ8Fr+y8GkLkRrzXGFHVe7I=";
    };
  };
  vscode-darwin-insider = {
    pname = "vscode-darwin-insider";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/2fb1c411a7933676c4efd18140f2a98fc910c945/VSCode-darwin.zip";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/2fb1c411a7933676c4efd18140f2a98fc910c945/VSCode-darwin.zip";
      sha256 = "sha256-Ksa9ic0yuIyfdOJbu1bnfyG43IiuV9yEaX++Dk1ee04=";
    };
  };
  vscode-darwin-stable = {
    pname = "vscode-darwin-stable";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/7e7950df89d055b5a378379db9ee14290772148a/VSCode-darwin.zip";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/7e7950df89d055b5a378379db9ee14290772148a/VSCode-darwin.zip";
      sha256 = "sha256-8tYtCq17eyrER06Td9IJ4rEMwOtn0w8/NkC5HGmJD/w=";
    };
  };
  vscode-linux-arm64-insider = {
    pname = "vscode-linux-arm64-insider";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/2fb1c411a7933676c4efd18140f2a98fc910c945/code-insider-arm64-1782450643.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/2fb1c411a7933676c4efd18140f2a98fc910c945/code-insider-arm64-1782450643.tar.gz";
      sha256 = "sha256-d1x7pYs1AjviCpYlpoE7+bOD5YX/lE89wJDCO4rNvOs=";
    };
  };
  vscode-linux-arm64-stable = {
    pname = "vscode-linux-arm64-stable";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/7e7950df89d055b5a378379db9ee14290772148a/code-stable-arm64-1782207906.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/7e7950df89d055b5a378379db9ee14290772148a/code-stable-arm64-1782207906.tar.gz";
      sha256 = "sha256-uKLo5Rpx3iD7zZlhq2HNbX3j+w0518HBtUZaRjzRweU=";
    };
  };
  vscode-linux-x64-insider = {
    pname = "vscode-linux-x64-insider";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/2fb1c411a7933676c4efd18140f2a98fc910c945/code-insider-x64-1782450637.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/2fb1c411a7933676c4efd18140f2a98fc910c945/code-insider-x64-1782450637.tar.gz";
      sha256 = "sha256-OYXjba/dnBkssaZau5OjRmndu0ChS0E/tbGFUVpgMN0=";
    };
  };
  vscode-linux-x64-stable = {
    pname = "vscode-linux-x64-stable";
    version = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/7e7950df89d055b5a378379db9ee14290772148a/code-stable-x64-1782207956.tar.gz";
    src = fetchTarball {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/stable/7e7950df89d055b5a378379db9ee14290772148a/code-stable-x64-1782207956.tar.gz";
      sha256 = "sha256-AAl2zIG3j5emO61EOhk9Vkl4xouHVMMWdklzqhsBic8=";
    };
  };
}
