# Regenerate with:
# nix-shell -p nvfetcher --command "nvfetcher -v --keep-going -c nvfetcher/obscura.toml -o generated/obscura"

[obscura-browser-bin-linux-x64]
src.github = "h4ckf0r0day/obscura"
fetch.tarball = "https://github.com/h4ckf0r0day/obscura/releases/download/$ver/obscura-x86_64-linux.tar.gz"

[obscura-browser-bin-linux-arm64]
src.github = "h4ckf0r0day/obscura"
fetch.tarball = "https://github.com/h4ckf0r0day/obscura/releases/download/$ver/obscura-aarch64-linux.tar.gz"

[obscura-browser-bin-darwin-x64]
src.github = "h4ckf0r0day/obscura"
fetch.tarball = "https://github.com/h4ckf0r0day/obscura/releases/download/$ver/obscura-x86_64-macos.tar.gz"

[obscura-browser-bin-darwin-arm64]
src.github = "h4ckf0r0day/obscura"
fetch.tarball = "https://github.com/h4ckf0r0day/obscura/releases/download/$ver/obscura-aarch64-macos.tar.gz"
