# Regenerate with:
# nix-shell -p nvfetcher --command "nvfetcher -v --keep-going -c nvfetcher/oh-my-pi.toml -o generated/oh-my-pi"

[oh-my-pi-darwin-arm64]
src.github = "can1357/oh-my-pi"
fetch.url = "https://github.com/can1357/oh-my-pi/releases/download/$ver/omp-darwin-arm64"

[oh-my-pi-darwin-x64]
src.github = "can1357/oh-my-pi"
fetch.url = "https://github.com/can1357/oh-my-pi/releases/download/$ver/omp-darwin-x64"

[oh-my-pi-linux-arm64]
src.github = "can1357/oh-my-pi"
fetch.url = "https://github.com/can1357/oh-my-pi/releases/download/$ver/omp-linux-arm64"

[oh-my-pi-linux-x64]
src.github = "can1357/oh-my-pi"
fetch.url = "https://github.com/can1357/oh-my-pi/releases/download/$ver/omp-linux-x64"
