name: Check

on:
  push:
    paths:
      - "**/*.nix"
      - "**/flake.lock"
      - ".github/workflows/check.yml"
  pull_request:
    paths:
      - "**/*.nix"
      - "**/flake.lock"
      - ".github/workflows/check.yml"
  workflow_dispatch:

concurrency:
  group: "check-${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}"
  cancel-in-progress: true

jobs:
  check:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15-intel]

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check
        run: NIXPKGS_ALLOW_UNFREE=1 nix flake check --impure
